package main

import "fmt"

/*
	64*(i&1) +
	4*(i&2)/2 +
	2*(i&4)/4 +
	1*(i&8)/8 +
	128*(i&16)/16 +
	32*(i&32)/32 +
	16*(i&64)/64 +
	8*(i&128)/128 +
*/

func main() {
	fmt.Printf("package braph\n")
	fmt.Printf("\n")
	fmt.Printf("// AUTOGENERATED see github.com/ohait/braph/tool\n")
	fmt.Printf("var chars = []rune{\n")

	for i := 0; i < 256; i++ {
		j := (0 +
			1*(i&1) +
			2*(i&2)/2 +
			4*(i&4)/4 +
			64*(i&8)/8 +
			8*(i&16)/16 +
			16*(i&32)/32 +
			32*(i&64)/64 +
			128*(i&128)/128 +
			0)
		r := '\u2800' + j
		fmt.Printf("    '\\u%x', // %c\n", (int)(r), r)
	}
	fmt.Printf("}\n")
}
